name: CI/CD Pipeline for .NET Core 8 with Docker

on:
  push:
    branches:
      - main  # Ejecuta el pipeline cuando hay cambios en la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Build Docker image
      - name: Build Docker Image
        run: docker build -t myapp:latest .

      # 3. Login to Render (Docker registry credentials)
      - name: Login to Render Docker Registry
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo $RENDER_API_KEY | docker login registry.render.com -u render --password-stdin

      # 4. Push Docker image to Render's registry
      - name: Push Docker Image
        run: docker push registry.render.com/your-service-id/myapp:latest

      # 5. Deploy using Render CLI
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -f https://cli.render.com/releases/v0.1.9/cli-linux-amd64 -o render
          chmod +x render
          ./render deploy --service <YOUR_SERVICE_ID>
